export const GAME_TO_VERSION_GROUP: Record<string, string> = {
  Red: "red-blue",
  Blue: "red-blue",
  Green: "red-blue",
  Yellow: "yellow",
  Gold: "gold-silver",
  Silver: "gold-silver",
  Crystal: "crystal",
  Ruby: "ruby-sapphire",
  Sapphire: "ruby-sapphire",
  Emerald: "emerald",
  FireRed: "firered-leafgreen",
  LeafGreen: "firered-leafgreen",
  Diamond: "diamond-pearl",
  Pearl: "diamond-pearl",
  Platinum: "platinum",
  HeartGold: "heartgold-soulsilver",
  SoulSilver: "heartgold-soulsilver",
  Black: "black-white",
  White: "black-white",
  "Black 2": "black-2-white-2",
  "White 2": "black-2-white-2",
  X: "x-y",
  Y: "x-y",
  "Omega Ruby": "omega-ruby-alpha-sapphire",
  "Alpha Sapphire": "omega-ruby-alpha-sapphire",
  Sun: "sun-moon",
  Moon: "sun-moon",
  "Ultra Sun": "ultra-sun-ultra-moon",
  "Ultra Moon": "ultra-sun-ultra-moon",
  Sword: "sword-shield",
  Shield: "sword-shield",
  "Brilliant Diamond": "brilliant-diamond-shining-pearl",
  "Shining Pearl": "brilliant-diamond-shining-pearl",
  Scarlet: "scarlet-violet",
  Violet: "scarlet-violet",
};
